# permissions for end users to edit logsinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logsink-editor-role
rules:
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks/status
  verbs:
  - get
