# permissions for end users to view logsinks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logsink-viewer-role
rules:
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks/status
  verbs:
  - get
