
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks/finalizers
  verbs:
  - update
- apiGroups:
  - log.carrefour.com
  resources:
  - logsinks/status
  verbs:
  - get
  - patch
  - update
